sudo: required
services:
  - docker

before_install:
  - docker build -t mayank/complex-react-test -f ./client/Dockerfile.dev ./client

script:
  # here -- --coverage will not keep the container hanging .. but will exit with exit code 0
  - docker run mayank/complex-react-test npm run test -- --coverage

after_success:
  - docker build -t mayankmaria/multi-client ./client
  - docker build -t mayankmaria/multi-nginx ./nginx
  - docker build -t mayankmaria/multi-server ./server
  - docker build -t mayankmaria/multi-worker ./worker

  #Take above images and move to docker hub.
  # Step 1. Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push docker images to docker id.
  - docker push mayankmaria/multi-client
  - docker push mayankmaria/multi-nginx
  - docker push mayankmaria/multi-server
  - docker push mayankmaria/multi-worker




# use this setting to deploy on aws
deploy:
  # this provider configuration is OOTB provided by travis ci
  provider: elasticbeanstalk
  # this is part of the elastic url
  region: "us-west-2"
  # name of the application created in aws
  app: "multi-docker"
  # env name in aws
  env: "MultiDocker-env"
  # copies the files from github and paste them in s3 bucket of aws
  bucket_name: "elasticbeanstalk-us-west-2-036834467397"
  # same as app name .. but will be listed in s3 storage
  bucket_path: "docker-multi"
  # only when master branch change happen deply in aws
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"